/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.services.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import sg.com.para.intranet.services.model.Expense;
import sg.com.para.intranet.services.model.ExpenseModel;
import sg.com.para.intranet.services.model.ExpenseSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Expense service. Represents a row in the &quot;intranet_expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link sg.com.para.intranet.services.model.ExpenseModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpenseImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see ExpenseImpl
 * @see sg.com.para.intranet.services.model.Expense
 * @see sg.com.para.intranet.services.model.ExpenseModel
 * @generated
 */
@JSON(strict = true)
public class ExpenseModelImpl extends BaseModelImpl<Expense>
	implements ExpenseModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a expense model instance should use the {@link sg.com.para.intranet.services.model.Expense} interface instead.
	 */
	public static final String TABLE_NAME = "intranet_expense";
	public static final Object[][] TABLE_COLUMNS = {
			{ "expenseId", Types.INTEGER },
			{ "employeeScreenName", Types.VARCHAR },
			{ "expenseDate", Types.TIMESTAMP },
			{ "submissionDate", Types.TIMESTAMP },
			{ "amount", Types.DOUBLE },
			{ "projectCode", Types.VARCHAR },
			{ "category", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "remarks", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table intranet_expense (expenseId INTEGER not null primary key,employeeScreenName VARCHAR(75) null,expenseDate DATE null,submissionDate DATE null,amount DOUBLE,projectCode VARCHAR(75) null,category VARCHAR(75) null,status VARCHAR(75) null,remarks VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table intranet_expense";
	public static final String ORDER_BY_JPQL = " ORDER BY expense.expenseId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY intranet_expense.expenseId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.sg.com.para.intranet.services.model.Expense"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.sg.com.para.intranet.services.model.Expense"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Expense toModel(ExpenseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Expense model = new ExpenseImpl();

		model.setExpenseId(soapModel.getExpenseId());
		model.setEmployeeScreenName(soapModel.getEmployeeScreenName());
		model.setExpenseDate(soapModel.getExpenseDate());
		model.setSubmissionDate(soapModel.getSubmissionDate());
		model.setAmount(soapModel.getAmount());
		model.setProjectCode(soapModel.getProjectCode());
		model.setCategory(soapModel.getCategory());
		model.setStatus(soapModel.getStatus());
		model.setRemarks(soapModel.getRemarks());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Expense> toModels(ExpenseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Expense> models = new ArrayList<Expense>(soapModels.length);

		for (ExpenseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.sg.com.para.intranet.services.model.Expense"));

	public ExpenseModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _expenseId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setExpenseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _expenseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Expense.class;
	}

	@Override
	public String getModelClassName() {
		return Expense.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("expenseId", getExpenseId());
		attributes.put("employeeScreenName", getEmployeeScreenName());
		attributes.put("expenseDate", getExpenseDate());
		attributes.put("submissionDate", getSubmissionDate());
		attributes.put("amount", getAmount());
		attributes.put("projectCode", getProjectCode());
		attributes.put("category", getCategory());
		attributes.put("status", getStatus());
		attributes.put("remarks", getRemarks());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer expenseId = (Integer)attributes.get("expenseId");

		if (expenseId != null) {
			setExpenseId(expenseId);
		}

		String employeeScreenName = (String)attributes.get("employeeScreenName");

		if (employeeScreenName != null) {
			setEmployeeScreenName(employeeScreenName);
		}

		Date expenseDate = (Date)attributes.get("expenseDate");

		if (expenseDate != null) {
			setExpenseDate(expenseDate);
		}

		Date submissionDate = (Date)attributes.get("submissionDate");

		if (submissionDate != null) {
			setSubmissionDate(submissionDate);
		}

		Double amount = (Double)attributes.get("amount");

		if (amount != null) {
			setAmount(amount);
		}

		String projectCode = (String)attributes.get("projectCode");

		if (projectCode != null) {
			setProjectCode(projectCode);
		}

		String category = (String)attributes.get("category");

		if (category != null) {
			setCategory(category);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String remarks = (String)attributes.get("remarks");

		if (remarks != null) {
			setRemarks(remarks);
		}
	}

	@JSON
	@Override
	public int getExpenseId() {
		return _expenseId;
	}

	@Override
	public void setExpenseId(int expenseId) {
		_expenseId = expenseId;
	}

	@JSON
	@Override
	public String getEmployeeScreenName() {
		if (_employeeScreenName == null) {
			return StringPool.BLANK;
		}
		else {
			return _employeeScreenName;
		}
	}

	@Override
	public void setEmployeeScreenName(String employeeScreenName) {
		_employeeScreenName = employeeScreenName;
	}

	@JSON
	@Override
	public Date getExpenseDate() {
		return _expenseDate;
	}

	@Override
	public void setExpenseDate(Date expenseDate) {
		_expenseDate = expenseDate;
	}

	@JSON
	@Override
	public Date getSubmissionDate() {
		return _submissionDate;
	}

	@Override
	public void setSubmissionDate(Date submissionDate) {
		_submissionDate = submissionDate;
	}

	@JSON
	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		_amount = amount;
	}

	@JSON
	@Override
	public String getProjectCode() {
		if (_projectCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _projectCode;
		}
	}

	@Override
	public void setProjectCode(String projectCode) {
		_projectCode = projectCode;
	}

	@JSON
	@Override
	public String getCategory() {
		if (_category == null) {
			return StringPool.BLANK;
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		_category = category;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@Override
	public Expense toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Expense)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExpenseImpl expenseImpl = new ExpenseImpl();

		expenseImpl.setExpenseId(getExpenseId());
		expenseImpl.setEmployeeScreenName(getEmployeeScreenName());
		expenseImpl.setExpenseDate(getExpenseDate());
		expenseImpl.setSubmissionDate(getSubmissionDate());
		expenseImpl.setAmount(getAmount());
		expenseImpl.setProjectCode(getProjectCode());
		expenseImpl.setCategory(getCategory());
		expenseImpl.setStatus(getStatus());
		expenseImpl.setRemarks(getRemarks());

		expenseImpl.resetOriginalValues();

		return expenseImpl;
	}

	@Override
	public int compareTo(Expense expense) {
		int primaryKey = expense.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Expense)) {
			return false;
		}

		Expense expense = (Expense)obj;

		int primaryKey = expense.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Expense> toCacheModel() {
		ExpenseCacheModel expenseCacheModel = new ExpenseCacheModel();

		expenseCacheModel.expenseId = getExpenseId();

		expenseCacheModel.employeeScreenName = getEmployeeScreenName();

		String employeeScreenName = expenseCacheModel.employeeScreenName;

		if ((employeeScreenName != null) && (employeeScreenName.length() == 0)) {
			expenseCacheModel.employeeScreenName = null;
		}

		Date expenseDate = getExpenseDate();

		if (expenseDate != null) {
			expenseCacheModel.expenseDate = expenseDate.getTime();
		}
		else {
			expenseCacheModel.expenseDate = Long.MIN_VALUE;
		}

		Date submissionDate = getSubmissionDate();

		if (submissionDate != null) {
			expenseCacheModel.submissionDate = submissionDate.getTime();
		}
		else {
			expenseCacheModel.submissionDate = Long.MIN_VALUE;
		}

		expenseCacheModel.amount = getAmount();

		expenseCacheModel.projectCode = getProjectCode();

		String projectCode = expenseCacheModel.projectCode;

		if ((projectCode != null) && (projectCode.length() == 0)) {
			expenseCacheModel.projectCode = null;
		}

		expenseCacheModel.category = getCategory();

		String category = expenseCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			expenseCacheModel.category = null;
		}

		expenseCacheModel.status = getStatus();

		String status = expenseCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			expenseCacheModel.status = null;
		}

		expenseCacheModel.remarks = getRemarks();

		String remarks = expenseCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			expenseCacheModel.remarks = null;
		}

		return expenseCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{expenseId=");
		sb.append(getExpenseId());
		sb.append(", employeeScreenName=");
		sb.append(getEmployeeScreenName());
		sb.append(", expenseDate=");
		sb.append(getExpenseDate());
		sb.append(", submissionDate=");
		sb.append(getSubmissionDate());
		sb.append(", amount=");
		sb.append(getAmount());
		sb.append(", projectCode=");
		sb.append(getProjectCode());
		sb.append(", category=");
		sb.append(getCategory());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("sg.com.para.intranet.services.model.Expense");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>expenseId</column-name><column-value><![CDATA[");
		sb.append(getExpenseId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeScreenName</column-name><column-value><![CDATA[");
		sb.append(getEmployeeScreenName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>expenseDate</column-name><column-value><![CDATA[");
		sb.append(getExpenseDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>submissionDate</column-name><column-value><![CDATA[");
		sb.append(getSubmissionDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>amount</column-name><column-value><![CDATA[");
		sb.append(getAmount());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectCode</column-name><column-value><![CDATA[");
		sb.append(getProjectCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>category</column-name><column-value><![CDATA[");
		sb.append(getCategory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Expense.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Expense.class
		};
	private int _expenseId;
	private String _employeeScreenName;
	private Date _expenseDate;
	private Date _submissionDate;
	private double _amount;
	private String _projectCode;
	private String _category;
	private String _status;
	private String _remarks;
	private Expense _escapedModel;
}