/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.services.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import sg.com.para.intranet.services.model.Timesheet;
import sg.com.para.intranet.services.model.TimesheetModel;
import sg.com.para.intranet.services.model.TimesheetSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Timesheet service. Represents a row in the &quot;intranet_timesheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link sg.com.para.intranet.services.model.TimesheetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimesheetImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see TimesheetImpl
 * @see sg.com.para.intranet.services.model.Timesheet
 * @see sg.com.para.intranet.services.model.TimesheetModel
 * @generated
 */
@JSON(strict = true)
public class TimesheetModelImpl extends BaseModelImpl<Timesheet>
	implements TimesheetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a timesheet model instance should use the {@link sg.com.para.intranet.services.model.Timesheet} interface instead.
	 */
	public static final String TABLE_NAME = "intranet_timesheet";
	public static final Object[][] TABLE_COLUMNS = {
			{ "timesheetId", Types.INTEGER },
			{ "employeeId", Types.INTEGER },
			{ "logDate", Types.TIMESTAMP },
			{ "regular", Types.DOUBLE },
			{ "overtime", Types.DOUBLE },
			{ "sick", Types.DOUBLE },
			{ "vacation", Types.DOUBLE },
			{ "holiday", Types.DOUBLE },
			{ "unpaid", Types.DOUBLE },
			{ "other", Types.DOUBLE },
			{ "remarks", Types.VARCHAR },
			{ "status", Types.DOUBLE },
			{ "projectId", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table intranet_timesheet (timesheetId INTEGER not null primary key,employeeId INTEGER,logDate DATE null,regular DOUBLE,overtime DOUBLE,sick DOUBLE,vacation DOUBLE,holiday DOUBLE,unpaid DOUBLE,other DOUBLE,remarks VARCHAR(75) null,status DOUBLE,projectId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table intranet_timesheet";
	public static final String ORDER_BY_JPQL = " ORDER BY timesheet.timesheetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY intranet_timesheet.timesheetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.sg.com.para.intranet.services.model.Timesheet"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.sg.com.para.intranet.services.model.Timesheet"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Timesheet toModel(TimesheetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Timesheet model = new TimesheetImpl();

		model.setTimesheetId(soapModel.getTimesheetId());
		model.setEmployeeId(soapModel.getEmployeeId());
		model.setLogDate(soapModel.getLogDate());
		model.setRegular(soapModel.getRegular());
		model.setOvertime(soapModel.getOvertime());
		model.setSick(soapModel.getSick());
		model.setVacation(soapModel.getVacation());
		model.setHoliday(soapModel.getHoliday());
		model.setUnpaid(soapModel.getUnpaid());
		model.setOther(soapModel.getOther());
		model.setRemarks(soapModel.getRemarks());
		model.setStatus(soapModel.getStatus());
		model.setProjectId(soapModel.getProjectId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Timesheet> toModels(TimesheetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Timesheet> models = new ArrayList<Timesheet>(soapModels.length);

		for (TimesheetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.sg.com.para.intranet.services.model.Timesheet"));

	public TimesheetModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _timesheetId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setTimesheetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _timesheetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Timesheet.class;
	}

	@Override
	public String getModelClassName() {
		return Timesheet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("timesheetId", getTimesheetId());
		attributes.put("employeeId", getEmployeeId());
		attributes.put("logDate", getLogDate());
		attributes.put("regular", getRegular());
		attributes.put("overtime", getOvertime());
		attributes.put("sick", getSick());
		attributes.put("vacation", getVacation());
		attributes.put("holiday", getHoliday());
		attributes.put("unpaid", getUnpaid());
		attributes.put("other", getOther());
		attributes.put("remarks", getRemarks());
		attributes.put("status", getStatus());
		attributes.put("projectId", getProjectId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer timesheetId = (Integer)attributes.get("timesheetId");

		if (timesheetId != null) {
			setTimesheetId(timesheetId);
		}

		Integer employeeId = (Integer)attributes.get("employeeId");

		if (employeeId != null) {
			setEmployeeId(employeeId);
		}

		Date logDate = (Date)attributes.get("logDate");

		if (logDate != null) {
			setLogDate(logDate);
		}

		Double regular = (Double)attributes.get("regular");

		if (regular != null) {
			setRegular(regular);
		}

		Double overtime = (Double)attributes.get("overtime");

		if (overtime != null) {
			setOvertime(overtime);
		}

		Double sick = (Double)attributes.get("sick");

		if (sick != null) {
			setSick(sick);
		}

		Double vacation = (Double)attributes.get("vacation");

		if (vacation != null) {
			setVacation(vacation);
		}

		Double holiday = (Double)attributes.get("holiday");

		if (holiday != null) {
			setHoliday(holiday);
		}

		Double unpaid = (Double)attributes.get("unpaid");

		if (unpaid != null) {
			setUnpaid(unpaid);
		}

		Double other = (Double)attributes.get("other");

		if (other != null) {
			setOther(other);
		}

		String remarks = (String)attributes.get("remarks");

		if (remarks != null) {
			setRemarks(remarks);
		}

		Double status = (Double)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Integer projectId = (Integer)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}
	}

	@JSON
	@Override
	public int getTimesheetId() {
		return _timesheetId;
	}

	@Override
	public void setTimesheetId(int timesheetId) {
		_timesheetId = timesheetId;
	}

	@JSON
	@Override
	public int getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(int employeeId) {
		_employeeId = employeeId;
	}

	@JSON
	@Override
	public Date getLogDate() {
		return _logDate;
	}

	@Override
	public void setLogDate(Date logDate) {
		_logDate = logDate;
	}

	@JSON
	@Override
	public double getRegular() {
		return _regular;
	}

	@Override
	public void setRegular(double regular) {
		_regular = regular;
	}

	@JSON
	@Override
	public double getOvertime() {
		return _overtime;
	}

	@Override
	public void setOvertime(double overtime) {
		_overtime = overtime;
	}

	@JSON
	@Override
	public double getSick() {
		return _sick;
	}

	@Override
	public void setSick(double sick) {
		_sick = sick;
	}

	@JSON
	@Override
	public double getVacation() {
		return _vacation;
	}

	@Override
	public void setVacation(double vacation) {
		_vacation = vacation;
	}

	@JSON
	@Override
	public double getHoliday() {
		return _holiday;
	}

	@Override
	public void setHoliday(double holiday) {
		_holiday = holiday;
	}

	@JSON
	@Override
	public double getUnpaid() {
		return _unpaid;
	}

	@Override
	public void setUnpaid(double unpaid) {
		_unpaid = unpaid;
	}

	@JSON
	@Override
	public double getOther() {
		return _other;
	}

	@Override
	public void setOther(double other) {
		_other = other;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@JSON
	@Override
	public double getStatus() {
		return _status;
	}

	@Override
	public void setStatus(double status) {
		_status = status;
	}

	@JSON
	@Override
	public int getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(int projectId) {
		_projectId = projectId;
	}

	@Override
	public Timesheet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Timesheet)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimesheetImpl timesheetImpl = new TimesheetImpl();

		timesheetImpl.setTimesheetId(getTimesheetId());
		timesheetImpl.setEmployeeId(getEmployeeId());
		timesheetImpl.setLogDate(getLogDate());
		timesheetImpl.setRegular(getRegular());
		timesheetImpl.setOvertime(getOvertime());
		timesheetImpl.setSick(getSick());
		timesheetImpl.setVacation(getVacation());
		timesheetImpl.setHoliday(getHoliday());
		timesheetImpl.setUnpaid(getUnpaid());
		timesheetImpl.setOther(getOther());
		timesheetImpl.setRemarks(getRemarks());
		timesheetImpl.setStatus(getStatus());
		timesheetImpl.setProjectId(getProjectId());

		timesheetImpl.resetOriginalValues();

		return timesheetImpl;
	}

	@Override
	public int compareTo(Timesheet timesheet) {
		int primaryKey = timesheet.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Timesheet)) {
			return false;
		}

		Timesheet timesheet = (Timesheet)obj;

		int primaryKey = timesheet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Timesheet> toCacheModel() {
		TimesheetCacheModel timesheetCacheModel = new TimesheetCacheModel();

		timesheetCacheModel.timesheetId = getTimesheetId();

		timesheetCacheModel.employeeId = getEmployeeId();

		Date logDate = getLogDate();

		if (logDate != null) {
			timesheetCacheModel.logDate = logDate.getTime();
		}
		else {
			timesheetCacheModel.logDate = Long.MIN_VALUE;
		}

		timesheetCacheModel.regular = getRegular();

		timesheetCacheModel.overtime = getOvertime();

		timesheetCacheModel.sick = getSick();

		timesheetCacheModel.vacation = getVacation();

		timesheetCacheModel.holiday = getHoliday();

		timesheetCacheModel.unpaid = getUnpaid();

		timesheetCacheModel.other = getOther();

		timesheetCacheModel.remarks = getRemarks();

		String remarks = timesheetCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			timesheetCacheModel.remarks = null;
		}

		timesheetCacheModel.status = getStatus();

		timesheetCacheModel.projectId = getProjectId();

		return timesheetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{timesheetId=");
		sb.append(getTimesheetId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append(", logDate=");
		sb.append(getLogDate());
		sb.append(", regular=");
		sb.append(getRegular());
		sb.append(", overtime=");
		sb.append(getOvertime());
		sb.append(", sick=");
		sb.append(getSick());
		sb.append(", vacation=");
		sb.append(getVacation());
		sb.append(", holiday=");
		sb.append(getHoliday());
		sb.append(", unpaid=");
		sb.append(getUnpaid());
		sb.append(", other=");
		sb.append(getOther());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("sg.com.para.intranet.services.model.Timesheet");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>timesheetId</column-name><column-value><![CDATA[");
		sb.append(getTimesheetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logDate</column-name><column-value><![CDATA[");
		sb.append(getLogDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regular</column-name><column-value><![CDATA[");
		sb.append(getRegular());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>overtime</column-name><column-value><![CDATA[");
		sb.append(getOvertime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sick</column-name><column-value><![CDATA[");
		sb.append(getSick());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacation</column-name><column-value><![CDATA[");
		sb.append(getVacation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>holiday</column-name><column-value><![CDATA[");
		sb.append(getHoliday());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unpaid</column-name><column-value><![CDATA[");
		sb.append(getUnpaid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>other</column-name><column-value><![CDATA[");
		sb.append(getOther());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Timesheet.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Timesheet.class
		};
	private int _timesheetId;
	private int _employeeId;
	private Date _logDate;
	private double _regular;
	private double _overtime;
	private double _sick;
	private double _vacation;
	private double _holiday;
	private double _unpaid;
	private double _other;
	private String _remarks;
	private double _status;
	private int _projectId;
	private Timesheet _escapedModel;
}